version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    # needs: db
    image: servik8888/kittygram_backend
    depends_on:
      - db:
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    # needs: backend
    image: servik8888/kittygram_frontend
    depends_on:
      - backend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    # needs: |
    #   backend
    #   frontend
    image: servik8888/kittygram_gateway
    depends_on:
      - backend
      - frontend
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media